from copy import deepcopy


DEFAULT_BANNERS: list[dict[str, object]] = [
    {
        "id": "banner-oil-transformer",
        "title": "Oil-Immersed Distribution Transformer",
        "subtitle": "MT-11 fully sealed transformer for stable medium and low-voltage power distribution.",
        "imageUrl": "/banner-assets/oil-immersed-transformer-banner.png",
        "linkUrl": "https://example.com/products/oil-immersed-distribution-transformer",
        "slot": "desktop",
        "enabled": True,
    },
    {
        "id": "banner-low-voltage-switchgear",
        "title": "Low-Voltage Complete Distribution Cabinets",
        "subtitle": "GEN-1 and GEN-2 switchgear cabinets for incoming lines, outgoing lines and reactive power compensation.",
        "imageUrl": "/banner-assets/low-voltage-switchgear-banner.png",
        "linkUrl": "https://example.com/products/low-voltage-complete-distribution-cabinet",
        "slot": "desktop",
        "enabled": True,
    },
    {
        "id": "banner-pv-box-substation",
        "title": "PV Box-type Step-up Substation",
        "subtitle": "YBM 10.5/0.8kV integrated PV substation for mountains, deserts and rooftop solar plants.",
        "imageUrl": "/banner-assets/pv-box-substation-banner.png",
        "linkUrl": "https://example.com/products/pv-box-type-substation",
        "slot": "desktop",
        "enabled": True,
    },
    {
        "id": "banner-smart-meter",
        "title": "Smart Energy Meter (AMI)",
        "subtitle": "Three-phase tariff-controlled smart meter with 4G, NB-IoT and LoRaWAN communication.",
        "imageUrl": "/banner-assets/smart-meter-banner.png",
        "linkUrl": "https://example.com/products/smart-ami-meter",
        "slot": "desktop",
        "enabled": True,
    },
]


DEFAULT_FAQ_CONFIG: dict[str, object] = {
    "eyebrow": "帮助中心 · ExampleCorp",
    "title": "常见问题",
    "accent": "解答",
    "summary": "面向印尼工业设备采购的一站式 EPC 解决方案。在这里快速找到关于采购流程、质量认证、价格起订量、物流清关、售后保障及热带环境适配的高频问答。",
    "searchPlaceholder": "搜索：下单流程、SNI 认证、起订量、DDP、防腐蚀…",
    "searchHint": "试试：模式 A · 质保 · 海风盐腐蚀",
    "allLabel": "全部",
    "popularLabel": "热门",
    "questionUnit": "个问题",
    "emptyTitle": "未找到相关问题",
    "emptyMessage": "换个关键词试试，或直接联系我们的工程师。",
    "emptyAction": "咨询工程师",
    "quickJumpLabel": "快速跳转",
    "ctaTitle": "仍有疑问？提交您的需求",
    "ctaBody": "描述您的应用场景与技术参数，平台工程师团队为您定制产品组合方案，并提供贴合印尼热带环境的整体打包报价。",
    "primaryAction": "提交需求",
    "secondaryAction": "浏览产品库",
    "primaryPath": "/contact",
    "secondaryPath": "/products",
    "translations": {
        "en": {
            "eyebrow": "Help Center · ExampleCorp",
            "title": "Frequently asked questions",
            "accent": "answered",
            "summary": "Find practical answers about sourcing, certification, MOQ, logistics, customs clearance, after-sales support and equipment selection for Indonesia's tropical environment.",
            "searchPlaceholder": "Search orders, SNI certification, MOQ, DDP or corrosion protection...",
            "searchHint": "Try: sourcing mode · warranty · coastal corrosion",
            "allLabel": "All",
            "popularLabel": "Popular",
            "questionUnit": "questions",
            "emptyTitle": "No matching questions",
            "emptyMessage": "Try another keyword or contact an engineer directly.",
            "emptyAction": "Contact an engineer",
            "quickJumpLabel": "Quick navigation",
            "ctaTitle": "Still have questions? Share your requirement",
            "ctaBody": "Describe the application and technical parameters. Our engineering team will prepare a product combination and project quotation for Indonesia.",
            "primaryAction": "Submit requirement",
            "secondaryAction": "Browse products",
        },
        "id": {
            "eyebrow": "Pusat Bantuan · ExampleCorp",
            "title": "Pertanyaan umum",
            "accent": "terjawab",
            "summary": "Temukan jawaban praktis tentang sourcing, sertifikasi, MOQ, logistik, bea cukai, after-sales, dan pemilihan peralatan untuk lingkungan tropis Indonesia.",
            "searchPlaceholder": "Cari proses order, sertifikasi SNI, MOQ, DDP, atau proteksi korosi...",
            "searchHint": "Coba: mode sourcing · garansi · korosi pantai",
            "allLabel": "Semua",
            "popularLabel": "Populer",
            "questionUnit": "pertanyaan",
            "emptyTitle": "Pertanyaan tidak ditemukan",
            "emptyMessage": "Coba kata kunci lain atau hubungi engineer kami.",
            "emptyAction": "Hubungi engineer",
            "quickJumpLabel": "Navigasi cepat",
            "ctaTitle": "Masih ada pertanyaan? Kirim kebutuhan Anda",
            "ctaBody": "Jelaskan aplikasi dan parameter teknis. Tim engineering kami akan menyiapkan kombinasi produk dan penawaran proyek untuk Indonesia.",
            "primaryAction": "Kirim kebutuhan",
            "secondaryAction": "Lihat produk",
        },
    },
    "categories": [
        {
            "id": "procurement",
            "icon": "list",
            "title": "采购流程",
            "titleTranslations": {"en": "Sourcing process", "id": "Proses sourcing"},
            "enabled": True,
            "items": [
                {
                    "id": "procurement-modes",
                    "question": "在 ExampleCorp 如何采购设备？",
                    "answer": "我们提供两种灵活模式，按需选择：\n\n模式 A — 自主选品，统一询价：浏览产品库 → 加入订单中心 → 平台统一核算报价。适合已明确规格参数的采购。\n\n模式 B — 提交需求，方案报价：描述应用场景与技术参数，工程师定制产品组合方案并整体打包报价。适合需要组合推荐的项目。\n\n两种模式均直连 5000+ 知名工业设备厂家，通过集中采购为您提供高性价比选择。",
                    "popular": True,
                },
                {
                    "id": "response-time",
                    "question": "提交需求后多久能收到响应？",
                    "answer": "通过提交需求页面发送后，工程师会在 1 个工作日内响应。完整产品组合方案报价通常需 2–3 个工作日，视场景复杂度而定。",
                },
                {
                    "id": "payment-methods",
                    "question": "支持哪些付款方式？",
                    "answer": "支持多种安全付款方式，包括电汇（T/T）、大额订单可走信用证（L/C），以及“付定金 + 发货前付尾款”的分阶段方式。具体付款条款会在报价中明确说明。",
                },
                {
                    "id": "free-consultation",
                    "question": "下单前可以免费咨询吗？",
                    "answer": "可以。工程师团队免费协助梳理需求、按项目所在地条件（含热带环境适配）调整规格，并给出产品组合建议，不收取前期咨询费用。直接发送您的项目场景即可。",
                },
            ],
        },
        {
            "id": "certification",
            "icon": "shield",
            "title": "质量与认证",
            "titleTranslations": {"en": "Quality and certification", "id": "Kualitas dan sertifikasi"},
            "enabled": True,
            "items": [
                {
                    "id": "standards",
                    "question": "产品是否符合 SNI、IEC、CE、ISO 标准？",
                    "answer": "符合。我们执行 SNI & IEC 标准，配备国际质量体系认证。认证路线覆盖欧盟、美国、中东和东南亚地区。出口产品资料与合规文件齐全，在发货前交付。",
                    "popular": True,
                },
                {
                    "id": "factory-inspection",
                    "question": "有工厂验厂和出货前检验吗？",
                    "answer": "有，这是核心服务之一。下单前我们会进行：\n\n工厂实地审计 — 核验生产线、ISO 认证和出口许可。\n\n出货前检验 — 确认样品与批量产品一致，杜绝到货与约定不符。\n\n目的：规避未经验证的供应商，确保交期与质量真实可靠。",
                },
                {
                    "id": "sample-order",
                    "question": "可以下样品单先验证再批量采购吗？",
                    "answer": "可以。我们提供样品单 → 试订单 → 批量单的分阶段推进路径，先验证兼容性与质量再放量，降低试错门槛。样品随附相关认证文件。",
                },
                {
                    "id": "compliance-risk",
                    "question": "如何避免到港后被退运？",
                    "answer": "我们提供认证前置服务：在付定金前先梳理目标市场的认证路线图（欧盟/美国/中东/东南亚），把合规要求提前到采购环节，避免“货到港才发现不合规”的退运风险。",
                },
            ],
        },
        {
            "id": "pricing",
            "icon": "price",
            "title": "价格与起订量",
            "titleTranslations": {"en": "Pricing and MOQ", "id": "Harga dan MOQ"},
            "enabled": True,
            "items": [
                {
                    "id": "moq",
                    "question": "起订量（MOQ）要求是多少？",
                    "answer": "我们提供低起订量与灵活订单。可从样品起步，再走试订单验证，最后批量下单。具体 MOQ 因产品类别和厂家而异，会在报价中注明。",
                    "popular": True,
                },
                {
                    "id": "tax-and-customs",
                    "question": "报价是否含税和清关费用？",
                    "answer": "取决于您选择的交付模式：\n\nDDP（完税后交货）：报价含报关、海运、清关、关税缴纳和尾程配送，端到端兜底。\n\nEXW（工厂交货）：您自行到工厂提货并处理物流，适合多工厂集中采购与二次集货。",
                },
                {
                    "id": "oem-odm",
                    "question": "支持 OEM/ODM 贴牌定制吗？",
                    "answer": "支持。我们提供 OEM/ODM 定制、多语言说明书和本地化包装。适合经销商或品牌方以自有标识转售。在提交需求时注明品牌定制要求即可。",
                },
                {
                    "id": "quotation-validity",
                    "question": "报价多久有效？",
                    "answer": "常规报价有效期 15–30 天（受原材料与汇率波动影响，以报价单标注为准）。若过期，可联系工程师重新核算，通常当天即可更新。",
                },
            ],
        },
        {
            "id": "logistics",
            "icon": "truck",
            "title": "物流与清关",
            "titleTranslations": {"en": "Logistics and customs", "id": "Logistik dan bea cukai"},
            "enabled": True,
            "items": [
                {
                    "id": "delivery-modes",
                    "question": "到印尼有哪些物流方式？",
                    "answer": "提供 DDP / EXW 双模式交付，灵活可控：\n\nDDP：我们报关、海运、印尼清关、关税缴纳并尾程配送到您的指定地点。\n\nEXW：您自提自运，适合有自有物流渠道的客户。\n\n总部、分部设有备件仓，可快速现场响应。",
                },
                {
                    "id": "delivery-time",
                    "question": "到印尼的运输周期大概多久？",
                    "answer": "运输周期视模式和库存而定：\n\n本地仓现货（总部/分部）：1–3 个工作日。\n\n生产 + 海运：4–8 周（含生产、验货、清关）。\n\n空运（加急）：可提供，费用较高。\n\n具体时间线在报价中按 SKU 与项目所在地给出。",
                },
                {
                    "id": "local-installation",
                    "question": "在印尼有本地安装指导吗？",
                    "answer": "有。作为印尼本地化服务的一部分，我们提供本地安装指导与售后支持体系。针对工业园区配电、光伏电站、充电桩、数据中心等项目，团队可到现场指导调试。",
                },
                {
                    "id": "customs-handling",
                    "question": "清关会遇到什么问题？我们如何处理？",
                    "answer": "印尼清关常见问题包括单证不全、SNI 标识缺失、HS 编码归类错误等。我们通过认证前置 + 单证齐全 + 本地清关经验提前规避，DDP 模式下全流程由我们兜底处理。",
                },
            ],
        },
        {
            "id": "after-sales",
            "icon": "service",
            "title": "售后保障",
            "titleTranslations": {"en": "After-sales support", "id": "Dukungan after-sales"},
            "enabled": True,
            "items": [
                {
                    "id": "warranty",
                    "question": "产品质保期多久？如何保修？",
                    "answer": "各品类均有质保，一般为 12–24 个月（开关柜等常规设备 12 个月，变压器更长）。质保期内出现质量问题，我们安排本地维修或更换备件。保修前会先验损确认。",
                },
                {
                    "id": "spare-parts",
                    "question": "采购后还能买到备件吗？",
                    "answer": "可以。我们建有双轨售后维修体系，总部、分部备件仓常备通用备件；特殊件可向厂家追单。交付不是服务的终点，技术问题我们持续协助。",
                },
                {
                    "id": "factory-repair",
                    "question": "本地修不了怎么办？能返厂吗？",
                    "answer": "两条路径保障：\n\n海外本地修 — 授权维修中心配原厂备件，覆盖常见故障。\n\n原厂返修 — 复杂故障可返厂维修，并同步提供备用机方案，确保您的运营不中断。",
                },
                {
                    "id": "maintenance-contract",
                    "question": "有定期维护合同吗？",
                    "answer": "可提供定期维护合同（可选），尤其针对关键设备（变压器、开关柜、逆变器）。定期巡检有助于延长在热带严苛环境下的使用寿命。下单洽谈时可一并提出。",
                },
            ],
        },
        {
            "id": "environment",
            "icon": "environment",
            "title": "规格与环境",
            "titleTranslations": {"en": "Specifications and environment", "id": "Spesifikasi dan lingkungan"},
            "enabled": True,
            "items": [
                {
                    "id": "tropical-environment",
                    "question": "如何保证设备能适应印尼的热带环境？",
                    "answer": "印尼具有高温、多雨、海风含盐易腐蚀的典型特征。提交需求时，工程师会据此推荐：\n\n户外/沿海：防护 IP66，材质 316 不锈钢或 SMC，环氧 + 聚氨酯涂层。\n\n室内/配电房：最低 IP4X，配防凝露加热器。\n\n电缆：选 XLPE 耐紫外耐潮外护套，不用普通 PVC。\n\n推荐参数会按您的项目所在地自动适配。",
                    "popular": True,
                },
                {
                    "id": "ip-rating",
                    "question": "应该选什么 IP 防护等级？",
                    "answer": "印尼通用选型指南：\n\nIP3X–IP4X：室内配电房，腐蚀风险低。\nIP54：有粉尘和湿气的车间。\nIP65：粉尘/油烟区，可能接触喷溅水。\nIP66：户外及沿海（必备），耐强力喷水。\nIP67：地下管廊/可能短时浸水区域。\n\n沿海地区选低 IP，约 6 个月就可能锈蚀。",
                },
                {
                    "id": "coastal-materials",
                    "question": "什么材质能抗海风盐腐蚀？",
                    "answer": "沿海/港口区域优先：\n\n316 不锈钢（不是 304，304 在沿海约 1 年就锈）。\nSMC 玻璃钢箱体，完全不锈。\n螺栓铰链也要 316，避免箱体 316 但螺栓 304。\n钢板表面采用热镀锌 + 环氧 + 聚氨酯三涂层，膜厚 ≥120μm。\n\n请供应商提供盐雾测试 NSS ≥720 小时无红锈报告。",
                },
                {
                    "id": "heat-and-humidity",
                    "question": "如何防止变压器/开关柜因高温潮湿损坏？",
                    "answer": "热带环境适配要点：\n\n降容使用：按额定容量的 80–85% 选型。\n变压器：室内选干式变压器（F/H 级）。\n开关柜：配防凝露加热器 + 温湿度控制器。\n绝缘等级：选 H 级（180℃）优于 B 级。\n防雷：配 SPD T1+T2 级浪涌保护，接地电阻 <4Ω。",
                },
                {
                    "id": "lightning-protection",
                    "question": "印尼雷电多，防雷接地怎么做？",
                    "answer": "印尼雷暴频次高，户外配电必须重视：\n\n配电柜加装 T1+T2 级 SPD 浪涌保护器。\n接地电阻 <4Ω，铜排需搪锡防氧化。\n进出线电缆两端做好屏蔽接地。\n关键设备前加装防雷模块组合方案，可由工程师配套。",
                },
            ],
        },
    ],
}


FAQ_ITEM_TRANSLATIONS: dict[str, dict[str, tuple[str, str]]] = {
    "procurement-modes": {
        "en": (
            "How can I source equipment through ExampleCorp?",
            "We offer two flexible sourcing modes:\n\nMode A — Select products and request one consolidated quotation: browse the product catalog → add items to the Order Center → receive a consolidated platform quotation. This is ideal when your specifications are already clear.\n\nMode B — Submit requirements and receive a proposed solution: describe the application and technical parameters, and our engineers will prepare a tailored product combination and bundled quotation. This is ideal for projects that need product recommendations.\n\nBoth modes connect you directly with more than 5,000 established power-equipment manufacturers and use consolidated purchasing to provide cost-effective options.",
        ),
        "id": (
            "Bagaimana cara membeli peralatan melalui ExampleCorp?",
            "Kami menyediakan dua mode sourcing yang fleksibel:\n\nMode A — Pilih produk dan minta satu penawaran terpadu: jelajahi katalog produk → tambahkan produk ke Pusat Pesanan → terima penawaran terpadu dari platform. Mode ini cocok jika spesifikasi Anda sudah jelas.\n\nMode B — Kirim kebutuhan dan terima solusi: jelaskan aplikasi serta parameter teknis, lalu engineer kami akan menyiapkan kombinasi produk dan penawaran paket. Mode ini cocok untuk proyek yang memerlukan rekomendasi produk.\n\nKedua mode menghubungkan Anda langsung dengan lebih dari 5.000 produsen peralatan listrik terkemuka dan memanfaatkan pembelian terpusat untuk memberikan pilihan yang hemat biaya.",
        ),
    },
    "response-time": {
        "en": ("How soon will I receive a response after submitting a requirement?", "An engineer will respond within one business day after you submit the requirement form. A complete product-combination proposal and quotation normally takes two to three business days, depending on project complexity."),
        "id": ("Berapa lama respons diterima setelah mengirim kebutuhan?", "Engineer kami akan merespons dalam satu hari kerja setelah formulir kebutuhan dikirim. Proposal kombinasi produk dan penawaran lengkap biasanya memerlukan dua hingga tiga hari kerja, tergantung kompleksitas proyek."),
    },
    "payment-methods": {
        "en": ("Which payment methods are supported?", "We support secure payment methods including bank transfer (T/T), letters of credit (L/C) for large orders, and staged payments with a deposit followed by the balance before shipment. The exact terms are stated clearly in the quotation."),
        "id": ("Metode pembayaran apa saja yang didukung?", "Kami mendukung metode pembayaran yang aman, termasuk transfer bank (T/T), letter of credit (L/C) untuk pesanan besar, serta pembayaran bertahap berupa uang muka dan pelunasan sebelum pengiriman. Ketentuan pastinya akan dijelaskan dalam penawaran."),
    },
    "free-consultation": {
        "en": ("Can I get a free consultation before ordering?", "Yes. Our engineers help clarify your requirements, adjust specifications for local project conditions—including tropical environments—and recommend a product combination at no preliminary consulting charge. Simply send us your project scenario."),
        "id": ("Apakah konsultasi sebelum memesan gratis?", "Ya. Engineer kami membantu memperjelas kebutuhan, menyesuaikan spesifikasi dengan kondisi lokasi proyek—termasuk lingkungan tropis—dan merekomendasikan kombinasi produk tanpa biaya konsultasi awal. Cukup kirimkan skenario proyek Anda."),
    },
    "standards": {
        "en": ("Do the products comply with SNI, IEC, CE and ISO standards?", "Yes. We supply products aligned with applicable SNI and IEC standards and supported by international quality-system certifications. Compliance routes cover the EU, the United States, the Middle East and Southeast Asia. Export documentation and compliance files are delivered before shipment."),
        "id": ("Apakah produk memenuhi standar SNI, IEC, CE, dan ISO?", "Ya. Kami memasok produk yang sesuai dengan standar SNI dan IEC yang berlaku serta didukung sertifikasi sistem mutu internasional. Jalur kepatuhan mencakup Uni Eropa, Amerika Serikat, Timur Tengah, dan Asia Tenggara. Dokumen ekspor dan kepatuhan diberikan sebelum pengiriman."),
    },
    "factory-inspection": {
        "en": ("Are factory audits and pre-shipment inspections available?", "Yes. These are core services. Before delivery we can perform:\n\nOn-site factory audit — verify production lines, ISO certifications and export licenses.\n\nPre-shipment inspection — confirm that mass-produced goods match approved samples and agreed specifications.\n\nThe goal is to avoid unverified suppliers and provide reliable quality and delivery schedules."),
        "id": ("Apakah tersedia audit pabrik dan inspeksi sebelum pengiriman?", "Ya. Keduanya merupakan layanan inti kami. Sebelum pengiriman kami dapat melakukan:\n\nAudit pabrik di lokasi — memverifikasi lini produksi, sertifikasi ISO, dan izin ekspor.\n\nInspeksi pra-pengiriman — memastikan produk massal sesuai dengan sampel yang disetujui dan spesifikasi yang disepakati.\n\nTujuannya adalah menghindari pemasok yang belum terverifikasi serta memastikan kualitas dan jadwal pengiriman yang andal."),
    },
    "sample-order": {
        "en": ("Can I validate a sample before placing a bulk order?", "Yes. We support a phased path from sample order to trial order and then bulk purchase. This lets you verify compatibility and quality before scaling up, reducing trial risk. Relevant certification documents are supplied with the sample."),
        "id": ("Bisakah saya memvalidasi sampel sebelum memesan dalam jumlah besar?", "Ya. Kami mendukung proses bertahap dari pesanan sampel ke pesanan uji, kemudian pembelian massal. Anda dapat memverifikasi kompatibilitas dan kualitas sebelum meningkatkan volume sehingga risiko uji coba lebih rendah. Dokumen sertifikasi terkait disertakan bersama sampel."),
    },
    "compliance-risk": {
        "en": ("How can I avoid cargo being rejected or returned at the destination port?", "We move compliance checks to the beginning of the sourcing process. Before the deposit is paid, we map the certification route for the target market—EU, US, Middle East or Southeast Asia—so requirements are addressed before production and the risk of discovering non-compliance after arrival is reduced."),
        "id": ("Bagaimana menghindari barang ditolak atau dikembalikan di pelabuhan tujuan?", "Kami menempatkan pemeriksaan kepatuhan di awal proses sourcing. Sebelum uang muka dibayar, kami memetakan jalur sertifikasi untuk pasar tujuan—Uni Eropa, Amerika Serikat, Timur Tengah, atau Asia Tenggara—agar persyaratan dipenuhi sebelum produksi dan risiko ketidaksesuaian setelah barang tiba dapat dikurangi."),
    },
    "moq": {
        "en": ("What is the minimum order quantity (MOQ)?", "We support low MOQs and flexible ordering. You can begin with a sample, proceed to a trial order and then place a bulk order. The exact MOQ varies by product category and manufacturer and is stated in the quotation."),
        "id": ("Berapa jumlah pesanan minimum (MOQ)?", "Kami mendukung MOQ rendah dan pemesanan yang fleksibel. Anda dapat memulai dengan sampel, melanjutkan ke pesanan uji, lalu melakukan pesanan massal. MOQ pasti berbeda menurut kategori produk dan produsen serta akan dicantumkan dalam penawaran."),
    },
    "tax-and-customs": {
        "en": ("Does the quotation include taxes and customs-clearance costs?", "It depends on the delivery term you choose:\n\nDDP (Delivered Duty Paid): the quotation includes export declaration, sea freight, import clearance, duties and final delivery to the destination.\n\nEXW (Ex Works): you collect the goods from the factory and manage logistics yourself. This is suitable for consolidating purchases from multiple factories."),
        "id": ("Apakah penawaran sudah termasuk pajak dan biaya bea cukai?", "Hal ini tergantung pada skema pengiriman yang dipilih:\n\nDDP (Delivered Duty Paid): penawaran mencakup deklarasi ekspor, angkutan laut, proses impor, pembayaran bea masuk, dan pengiriman akhir ke lokasi tujuan.\n\nEXW (Ex Works): Anda mengambil barang di pabrik dan mengelola logistik sendiri. Skema ini cocok untuk konsolidasi pembelian dari beberapa pabrik."),
    },
    "oem-odm": {
        "en": ("Do you support OEM/ODM and private-label customization?", "Yes. We support OEM/ODM customization, multilingual manuals and localized packaging for distributors and brand owners selling under their own identity. Include your branding requirements when submitting the inquiry."),
        "id": ("Apakah tersedia OEM/ODM dan kustomisasi merek pribadi?", "Ya. Kami mendukung kustomisasi OEM/ODM, manual multibahasa, dan kemasan lokal untuk distributor atau pemilik merek yang menjual dengan identitas sendiri. Cantumkan kebutuhan merek Anda saat mengirim permintaan."),
    },
    "quotation-validity": {
        "en": ("How long is a quotation valid?", "Standard quotations are usually valid for 15 to 30 days, subject to raw-material prices and exchange-rate movements. The exact validity is shown on the quotation. If it expires, an engineer can normally recalculate it the same day."),
        "id": ("Berapa lama masa berlaku penawaran?", "Penawaran standar biasanya berlaku selama 15 hingga 30 hari, tergantung perubahan harga bahan baku dan nilai tukar. Masa berlaku pasti tercantum pada dokumen penawaran. Jika kedaluwarsa, engineer biasanya dapat menghitung ulang pada hari yang sama."),
    },
    "delivery-modes": {
        "en": ("Which shipping options are available for Indonesia?", "We offer flexible DDP and EXW delivery:\n\nDDP: we manage export declaration, sea freight, Indonesian customs clearance, duties and final delivery to your specified location.\n\nEXW: you collect and transport the goods using your own logistics channel.\n\nSpare-parts warehouses in Head Office and Branch Office support rapid local response."),
        "id": ("Pilihan pengiriman apa yang tersedia untuk Indonesia?", "Kami menawarkan pengiriman DDP dan EXW yang fleksibel:\n\nDDP: kami mengelola deklarasi ekspor, angkutan laut, bea cukai Indonesia, pembayaran bea masuk, dan pengiriman akhir ke lokasi yang Anda tentukan.\n\nEXW: Anda mengambil dan mengangkut barang menggunakan jalur logistik sendiri.\n\nGudang suku cadang di Head Office dan Branch Office mendukung respons lokal yang cepat."),
    },
    "delivery-time": {
        "en": ("How long does delivery to Indonesia take?", "Lead time depends on the delivery method and stock status:\n\nLocal stock in Head Office or Branch Office: 1–3 business days.\n\nProduction plus sea freight: 4–8 weeks, including production, inspection and customs clearance.\n\nAir freight for urgent orders: available at a higher cost.\n\nThe quotation provides an SKU- and location-specific timeline."),
        "id": ("Berapa lama waktu pengiriman ke Indonesia?", "Waktu pengiriman tergantung pada metode dan ketersediaan stok:\n\nStok lokal di Head Office atau Branch Office: 1–3 hari kerja.\n\nProduksi dan angkutan laut: 4–8 minggu, termasuk produksi, inspeksi, dan bea cukai.\n\nAngkutan udara untuk kebutuhan mendesak: tersedia dengan biaya lebih tinggi.\n\nPenawaran akan mencantumkan jadwal berdasarkan SKU dan lokasi proyek."),
    },
    "local-installation": {
        "en": ("Is local installation guidance available in Indonesia?", "Yes. Our localized service in Indonesia includes installation guidance and after-sales support. For industrial distribution, solar plants, EV charging, data centers and similar projects, our team can provide on-site commissioning guidance."),
        "id": ("Apakah tersedia panduan instalasi lokal di Indonesia?", "Ya. Layanan lokal kami di Indonesia mencakup panduan instalasi dan dukungan after-sales. Untuk proyek distribusi kawasan industri, pembangkit surya, pengisian kendaraan listrik, pusat data, dan proyek serupa, tim kami dapat memberikan panduan commissioning di lokasi."),
    },
    "customs-handling": {
        "en": ("What customs-clearance issues may arise, and how are they handled?", "Common Indonesian clearance issues include incomplete documents, missing SNI markings and incorrect HS-code classification. We reduce these risks through early certification planning, complete documentation and local customs experience. Under DDP terms, we manage the full clearance process."),
        "id": ("Masalah apa yang dapat terjadi saat bea cukai, dan bagaimana penanganannya?", "Masalah umum pada proses bea cukai Indonesia meliputi dokumen tidak lengkap, penandaan SNI yang tidak ada, dan klasifikasi kode HS yang keliru. Kami mengurangi risiko tersebut melalui perencanaan sertifikasi sejak awal, dokumen lengkap, dan pengalaman bea cukai lokal. Dalam skema DDP, kami menangani seluruh prosesnya."),
    },
    "warranty": {
        "en": ("How long is the warranty, and how are claims handled?", "All product categories carry a warranty, normally 12–24 months. Standard equipment such as switchgear is typically covered for 12 months, while transformers may have longer coverage. For verified quality issues during the warranty period, we arrange local repair or replacement parts after damage assessment."),
        "id": ("Berapa lama garansi produk dan bagaimana proses klaimnya?", "Semua kategori produk memiliki garansi, biasanya 12–24 bulan. Peralatan standar seperti switchgear umumnya bergaransi 12 bulan, sedangkan trafo dapat memiliki masa lebih panjang. Untuk masalah kualitas yang terverifikasi selama masa garansi, kami mengatur perbaikan lokal atau penggantian suku cadang setelah pemeriksaan kerusakan."),
    },
    "spare-parts": {
        "en": ("Can I still purchase spare parts after delivery?", "Yes. Our two-track after-sales system keeps common spare parts in Head Office and Branch Office, while special parts can be reordered from the manufacturer. Delivery is not the end of our service; we continue to assist with technical issues."),
        "id": ("Apakah suku cadang masih dapat dibeli setelah pengiriman?", "Ya. Sistem after-sales dua jalur kami menyimpan suku cadang umum di Head Office dan Branch Office, sedangkan komponen khusus dapat dipesan kembali dari produsen. Pengiriman bukan akhir layanan kami; kami tetap membantu menangani masalah teknis."),
    },
    "factory-repair": {
        "en": ("What if the equipment cannot be repaired locally? Can it be returned to the factory?", "Two service paths are available:\n\nLocal overseas repair — authorized service centers use original spare parts for common faults.\n\nFactory repair — complex faults can be returned to the manufacturer, with a standby-unit plan arranged where applicable to reduce operational interruption."),
        "id": ("Bagaimana jika peralatan tidak dapat diperbaiki secara lokal? Apakah bisa dikirim kembali ke pabrik?", "Tersedia dua jalur layanan:\n\nPerbaikan lokal — pusat servis resmi menggunakan suku cadang asli untuk menangani kerusakan umum.\n\nPerbaikan pabrik — kerusakan kompleks dapat dikirim kembali ke produsen, disertai rencana unit cadangan bila memungkinkan untuk mengurangi gangguan operasional."),
    },
    "maintenance-contract": {
        "en": ("Are scheduled maintenance contracts available?", "Optional scheduled maintenance contracts are available, especially for critical equipment such as transformers, switchgear and inverters. Regular inspections can extend service life in harsh tropical conditions. Request this option during order discussions."),
        "id": ("Apakah tersedia kontrak pemeliharaan berkala?", "Kontrak pemeliharaan berkala tersedia sebagai opsi, terutama untuk peralatan penting seperti trafo, switchgear, dan inverter. Inspeksi rutin dapat memperpanjang umur pakai di kondisi tropis yang berat. Sampaikan kebutuhan ini saat membahas pesanan."),
    },
    "tropical-environment": {
        "en": ("How do you ensure equipment is suitable for Indonesia's tropical environment?", "Indonesia combines high temperatures, heavy rainfall, humidity and salt-laden coastal air. Based on the project location, our engineers may recommend:\n\nOutdoor or coastal use: IP66 protection, 316 stainless steel or SMC enclosures, and epoxy plus polyurethane coatings.\n\nIndoor switch rooms: at least IP4X with anti-condensation heaters.\n\nCables: UV- and moisture-resistant XLPE outer sheaths instead of ordinary PVC.\n\nRecommended specifications are adapted to the conditions at your project site."),
        "id": ("Bagaimana memastikan peralatan sesuai untuk lingkungan tropis Indonesia?", "Indonesia memiliki suhu tinggi, curah hujan besar, kelembapan, dan udara pantai yang mengandung garam. Berdasarkan lokasi proyek, engineer kami dapat merekomendasikan:\n\nPenggunaan luar ruang atau pesisir: proteksi IP66, enclosure stainless steel 316 atau SMC, serta lapisan epoksi dan poliuretan.\n\nRuang panel dalam ruangan: minimal IP4X dengan pemanas anti-kondensasi.\n\nKabel: selubung luar XLPE tahan UV dan kelembapan, bukan PVC biasa.\n\nSpesifikasi rekomendasi disesuaikan dengan kondisi lokasi proyek Anda."),
    },
    "ip-rating": {
        "en": ("Which IP protection rating should I choose?", "General selection guide for Indonesia:\n\nIP3X–IP4X: indoor switch rooms with low corrosion risk.\nIP54: workshops with dust and humidity.\nIP65: dusty or oily areas exposed to water spray.\nIP66: required for outdoor and coastal use; resistant to powerful water jets.\nIP67: underground corridors or areas subject to temporary immersion.\n\nA low IP rating in coastal areas can lead to corrosion in about six months."),
        "id": ("Tingkat proteksi IP apa yang sebaiknya dipilih?", "Panduan umum pemilihan untuk Indonesia:\n\nIP3X–IP4X: ruang panel dalam ruangan dengan risiko korosi rendah.\nIP54: bengkel dengan debu dan kelembapan.\nIP65: area berdebu atau berminyak yang dapat terkena semprotan air.\nIP66: wajib untuk luar ruang dan pesisir; tahan semburan air kuat.\nIP67: koridor bawah tanah atau area yang mungkin terendam sementara.\n\nTingkat IP yang rendah di wilayah pesisir dapat menyebabkan korosi dalam sekitar enam bulan."),
    },
    "coastal-materials": {
        "en": ("Which materials resist salt-air corrosion in coastal areas?", "For coastal and port areas, prioritize:\n\n316 stainless steel rather than 304, which may corrode near the coast within about one year.\nSMC fiberglass enclosures, which do not rust.\n316 bolts and hinges as well as the enclosure; avoid combining a 316 enclosure with 304 fasteners.\nHot-dip galvanizing plus epoxy and polyurethane on steel plate, with total coating thickness of at least 120 μm.\n\nAsk the supplier for an NSS salt-spray test report showing at least 720 hours without red rust."),
        "id": ("Material apa yang tahan korosi udara asin di wilayah pesisir?", "Untuk wilayah pesisir dan pelabuhan, prioritaskan:\n\nStainless steel 316, bukan 304 yang dapat berkarat di pesisir dalam sekitar satu tahun.\nEnclosure fiberglass SMC yang tidak berkarat.\nBaut dan engsel 316, bukan enclosure 316 yang dipadukan dengan pengikat 304.\nPelat baja dengan galvanisasi celup panas, epoksi, dan poliuretan, dengan ketebalan total lapisan minimal 120 μm.\n\nMinta pemasok memberikan laporan uji semprot garam NSS minimal 720 jam tanpa karat merah."),
    },
    "heat-and-humidity": {
        "en": ("How can transformers and switchgear be protected from heat and humidity?", "Key measures for tropical conditions:\n\nDerating: select equipment to operate at 80–85% of rated capacity.\nTransformers: use dry-type units with Class F or H insulation indoors.\nSwitchgear: install anti-condensation heaters and temperature/humidity controllers.\nInsulation: Class H (180°C) is preferable to Class B.\nSurge protection: use Type 1+2 SPD protection and keep grounding resistance below 4 Ω."),
        "id": ("Bagaimana melindungi trafo dan switchgear dari panas serta kelembapan?", "Langkah utama untuk kondisi tropis:\n\nDerating: pilih peralatan agar beroperasi pada 80–85% kapasitas nominal.\nTrafo: gunakan trafo kering dengan kelas isolasi F atau H untuk dalam ruangan.\nSwitchgear: pasang pemanas anti-kondensasi dan pengontrol suhu/kelembapan.\nIsolasi: kelas H (180°C) lebih baik daripada kelas B.\nProteksi surja: gunakan SPD Tipe 1+2 dan jaga resistansi pembumian di bawah 4 Ω."),
    },
    "lightning-protection": {
        "en": ("Indonesia has frequent lightning. How should surge protection and grounding be designed?", "Because thunderstorms are frequent in Indonesia, outdoor distribution systems require careful protection:\n\nInstall Type 1+2 SPD surge protection in distribution panels.\nKeep grounding resistance below 4 Ω and tin copper busbars to reduce oxidation.\nProvide shield grounding at both ends of incoming and outgoing cables.\nUse a coordinated lightning-protection module package before critical equipment; our engineers can specify the combination."),
        "id": ("Petir sering terjadi di Indonesia. Bagaimana merancang proteksi surja dan pembumian?", "Karena badai petir sering terjadi di Indonesia, sistem distribusi luar ruang memerlukan perlindungan khusus:\n\nPasang SPD Tipe 1+2 pada panel distribusi.\nJaga resistansi pembumian di bawah 4 Ω dan lapisi busbar tembaga dengan timah untuk mengurangi oksidasi.\nLakukan pembumian pelindung pada kedua ujung kabel masuk dan keluar.\nGunakan paket modul proteksi petir yang terkoordinasi sebelum peralatan penting; engineer kami dapat menentukan kombinasinya."),
    },
}


for faq_category in DEFAULT_FAQ_CONFIG["categories"]:
    for faq_item in faq_category["items"]:
        translations = FAQ_ITEM_TRANSLATIONS[str(faq_item["id"])]
        faq_item["questionTranslations"] = {
            locale: content[0] for locale, content in translations.items()
        }
        faq_item["answerTranslations"] = {
            locale: content[1] for locale, content in translations.items()
        }


DEFAULT_WEBSITE_CONFIG: dict[str, object] = {
    "homeSections": [
        {
            "id": "hero",
            "name": "首页 Banner",
            "anchor": "home.hero",
            "description": "首页第一屏轮播图和核心价值文案。",
            "enabled": True,
        },
        {
            "id": "featured-products",
            "name": "Hot Products",
            "anchor": "home.featured_products",
            "description": "首页第二顺序展示的重点产品和优先 SKU。",
            "enabled": True,
        },
        {
            "id": "solutions",
            "name": "解决方案",
            "anchor": "home.solutions",
            "description": "行业场景和项目解决方案卡片。",
            "enabled": True,
        },
        {
            "id": "about",
            "name": "关于我们",
            "anchor": "home.about",
            "description": "工厂能力、合作伙伴和质量保证内容。",
            "enabled": True,
        },
        {
            "id": "inquiry",
            "name": "询盘转化",
            "anchor": "home.inquiry",
            "description": "WhatsApp、邮箱和询盘入口。",
            "enabled": True,
        },
    ],
    "banners": DEFAULT_BANNERS,
    "faq": DEFAULT_FAQ_CONFIG,
    "bannerCarousel": {
        "autoplay": True,
        "intervalSeconds": 5,
    },
    "searchSettings": {
        "placeholder": "输入应用场景、设备需求或技术参数，如：工业园区配电改造...",
    },
    "homeText": [
        {
            "key": "allCategories",
            "label": "全部产品分类",
            "value": "全部产品分类",
            "translations": {"en": "All product categories", "zh-CN": "全部产品分类", "id": "Semua kategori produk"},
        },
        {
            "key": "demandPlaceholder",
            "label": "首页询盘输入提示",
            "value": "请描述您的用电需求（如：315kVA变压器采购），并留下您的联系电话和邮箱，以便我们及时为您提供方案报价...",
            "translations": {
                "en": "Describe your power demand, e.g. 315kVA transformer purchase, and leave phone or email so we can prepare a proposal...",
                "zh-CN": "请描述您的用电需求（如：315kVA变压器采购），并留下您的联系电话和邮箱，以便我们及时为您提供方案报价...",
                "id": "Jelaskan kebutuhan daya Anda, mis. pembelian trafo 315kVA, dan tinggalkan email/telepon untuk proposal...",
            },
        },
        {
            "key": "email",
            "label": "邮箱字段",
            "value": "邮箱",
            "translations": {"en": "Email", "zh-CN": "邮箱", "id": "Email"},
        },
        {
            "key": "phone",
            "label": "电话字段",
            "value": "电话",
            "translations": {"en": "Phone", "zh-CN": "电话", "id": "Telepon"},
        },
        {
            "key": "submit",
            "label": "提交按钮",
            "value": "一键提交需求",
            "translations": {"en": "Submit requirement", "zh-CN": "一键提交需求", "id": "Kirim kebutuhan"},
        },
        {
            "key": "attach",
            "label": "附件按钮",
            "value": "上传附件",
            "translations": {"en": "Attach file", "zh-CN": "上传附件", "id": "Lampirkan file"},
        },
        {
            "key": "voice",
            "label": "语音按钮",
            "value": "语音输入",
            "translations": {"en": "Voice input", "zh-CN": "语音输入", "id": "Input suara"},
        },
        {
            "key": "listening",
            "label": "语音识别中",
            "value": "识别中...",
            "translations": {"en": "Listening...", "zh-CN": "识别中...", "id": "Mendengarkan..."},
        },
        {
            "key": "voiceUnsupported",
            "label": "不支持语音提示",
            "value": "当前浏览器不支持语音输入。",
            "translations": {
                "en": "Voice input is not supported in this browser.",
                "zh-CN": "当前浏览器不支持语音输入。",
                "id": "Voice input is not supported in this browser.",
            },
        },
        {
            "key": "voiceRequiresSecureContext",
            "label": "语音需要安全环境提示",
            "value": "语音输入需要 HTTPS 或 localhost 环境。",
            "translations": {
                "en": "Voice input requires HTTPS or localhost.",
                "zh-CN": "语音输入需要 HTTPS 或 localhost 环境。",
                "id": "Input suara memerlukan HTTPS atau localhost.",
            },
        },
        {
            "key": "contactRequired",
            "label": "联系方式必填提示",
            "value": "留下您的联系电话和邮箱，以便解决您的需求",
            "translations": {
                "en": "Please leave your phone or email so we can respond to your requirement.",
                "zh-CN": "留下您的联系电话和邮箱，以便解决您的需求",
                "id": "留下您的联系电话和邮箱，以便解决您的需求",
            },
        },
        {
            "key": "viewMore",
            "label": "查看更多",
            "value": "查看更多",
            "translations": {"en": "View more", "zh-CN": "查看更多", "id": "Lihat lainnya"},
        },
        {
            "key": "moreScenes",
            "label": "更多场景",
            "value": "更多场景",
            "translations": {"en": "More scenarios", "zh-CN": "更多场景", "id": "Skenario lainnya"},
        },
        {
            "key": "productCategories",
            "label": "产品分类标题",
            "value": "产品分类",
            "translations": {"en": "Product categories", "zh-CN": "产品分类", "id": "Kategori produk"},
        },
        {
            "key": "suppliers",
            "label": "供应商标题",
            "value": "战略合作供应商",
            "translations": {"en": "Strategic partner suppliers", "zh-CN": "战略合作供应商", "id": "Mitra pemasok strategis"},
        },
        {
            "key": "supplierSystem",
            "label": "供应链按钮",
            "value": "查看供应链体系",
            "translations": {"en": "View supply chain system", "zh-CN": "查看供应链体系", "id": "Lihat sistem rantai pasok"},
        },
        {
            "key": "defaultName",
            "label": "首页询盘默认姓名",
            "value": "首页访客",
            "translations": {"en": "Homepage visitor", "zh-CN": "首页访客", "id": "Pengunjung beranda"},
        },
        {
            "key": "defaultCompany",
            "label": "首页询盘默认公司",
            "value": "首页直接询盘",
            "translations": {"en": "Direct homepage inquiry", "zh-CN": "首页直接询盘", "id": "Inquiry langsung dari beranda"},
        },
    ],
    "featureCards": [
        {
            "id": "feature-oem",
            "icon": "building",
            "title": "OEM/ODM Solutions",
            "content": "Tailored manufacturing, branding and engineering support for long-term electrical projects.",
            "enabled": True,
        },
        {
            "id": "feature-certified",
            "icon": "badge",
            "title": "ISO & CE Certified",
            "content": "Factory-controlled production with internationally recognized quality and compliance standards.",
            "enabled": True,
        },
        {
            "id": "feature-shipping",
            "icon": "package",
            "title": "Fast Global Shipping",
            "content": "Export-ready packing, documentation and stable delivery schedules for overseas buyers.",
            "enabled": True,
        },
        {
            "id": "feature-support",
            "icon": "headphones",
            "title": "24/7 Support",
            "content": "Responsive pre-sales, after-sales and technical communication across project stages.",
            "enabled": True,
        },
    ],
    "platformSellingPoints": [
        {
            "id": "platform-delivery",
            "icon": "globe",
            "title": "一站式EPC解决",
            "content": "统一负责，直连5000+知名工业设备厂家，通过集中采购为印尼买家提供高性价比的产品选择。",
            "titleTranslations": {
                "en": "One-stop EPC solution",
                "zh-CN": "一站式EPC解决",
                "id": "Solusi EPC terpadu",
            },
            "contentTranslations": {
                "en": "One accountable partner connecting buyers directly with 5,000+ established power equipment manufacturers, using consolidated procurement to deliver cost-effective product choices for Indonesian buyers.",
                "zh-CN": "统一负责，直连5000+知名工业设备厂家，通过集中采购为印尼买家提供高性价比的产品选择。",
                "id": "Satu pihak bertanggung jawab, menghubungkan pembeli langsung dengan 5.000+ produsen peralatan listrik ternama, serta menyediakan pilihan produk bernilai tinggi bagi pembeli Indonesia melalui pengadaan terpusat.",
            },
            "enabled": True,
        },
        {
            "id": "platform-service",
            "icon": "headphones",
            "title": "印尼本地化服务",
            "content": "快速现场响应，总部/分部备件仓，本地安装指导与售后支持体系。",
            "titleTranslations": {
                "en": "Localized service in Indonesia",
                "zh-CN": "印尼本地化服务",
                "id": "Layanan lokal Indonesia",
            },
            "contentTranslations": {
                "en": "Rapid on-site response, spare-parts warehouses in Head Office and Branch Office, plus local installation guidance and after-sales support.",
                "zh-CN": "快速现场响应，总部/分部备件仓，本地安装指导与售后支持体系。",
                "id": "Respons cepat di lokasi, gudang suku cadang di Head Office dan Branch Office, serta panduan instalasi lokal dan dukungan purnajual.",
            },
            "enabled": True,
        },
        {
            "id": "platform-certified",
            "icon": "shield",
            "title": "SNI&IEC标准",
            "content": "国际质量体系认证，出口产品资料与合规文件齐全。",
            "titleTranslations": {
                "en": "SNI & IEC standards",
                "zh-CN": "SNI&IEC标准",
                "id": "Standar SNI & IEC",
            },
            "contentTranslations": {
                "en": "International quality system certification with complete export product documentation and compliance files.",
                "zh-CN": "国际质量体系认证，出口产品资料与合规文件齐全。",
                "id": "Sertifikasi sistem mutu internasional dengan dokumentasi produk ekspor dan berkas kepatuhan yang lengkap.",
            },
            "enabled": True,
        },
    ],
    "homeWhyChoose": {
        "title": "为什么选择 ExampleCorp",
        "ctaText": "了解平台详情",
        "titleTranslations": {
            "en": "Why choose ExampleCorp",
            "zh-CN": "为什么选择 ExampleCorp",
            "id": "Mengapa memilih ExampleCorp",
        },
        "ctaTextTranslations": {
            "en": "Learn platform details",
            "zh-CN": "了解平台详情",
            "id": "Pelajari detail platform",
        },
        "reasons": [
            {
                "id": "reason-ai-sourcing",
                "number": "1",
                "title": "AI 智能采购",
                "subtitle": "精准匹配，告别大海捞针",
                "quote": "很多海外买家只知道哪里已是或环球资源，但痛点在于验证供应商是否真的有出口经验、认证和真实产能。",
                "bullets": ["链接超过 500+ 经过验证的工业设备制造商", "AI 根据应用场景、电压标准、起订量和预算匹配供应商"],
                "titleTranslations": {"en": "AI-assisted sourcing", "zh-CN": "AI 智能采购", "id": "Sourcing berbantu AI"},
                "subtitleTranslations": {"en": "Accurate matching across product categories", "zh-CN": "精准匹配，告别大海捞针", "id": "Pencocokan akurat lintas kategori"},
                "quoteTranslations": {"en": "Reduce supplier search time and avoid unverified overseas vendors.", "zh-CN": "很多海外买家只知道哪里已是或环球资源，但痛点在于验证供应商是否真的有出口经验、认证和真实产能。", "id": "Kurangi waktu mencari pemasok dan hindari vendor yang belum terverifikasi."},
                "bulletTranslations": {"en": ["Match application, voltage, MOQ and budget to pre-reviewed suppliers", "Shorten sourcing time with direct factory quotes"], "zh-CN": ["链接超过 500+ 经过验证的工业设备制造商", "AI 根据应用场景、电压标准、起订量和预算匹配供应商"], "id": ["Cocokkan aplikasi, tegangan, MOQ dan anggaran", "Percepat sourcing dengan quote pabrik langsung"]},
                "enabled": True,
            },
            {
                "id": "reason-factory-audit",
                "number": "2",
                "title": "工厂验厂与质检",
                "subtitle": "实地验货，杜绝踩坑",
                "quote": "我们对供应商进行实地考察，确保其产品质量和交期真实可靠。",
                "bullets": ["实地工厂审计，核验生产线、ISO 认证和出口许可", "出货前检验，确认样品与批量产品一致"],
                "titleTranslations": {"en": "Factory audit and inspection", "zh-CN": "工厂验厂与质检", "id": "Audit pabrik dan inspeksi"},
                "subtitleTranslations": {"en": "Verify capacity before order", "zh-CN": "实地验货，杜绝踩坑", "id": "Verifikasi sebelum order"},
                "quoteTranslations": {"en": "We inspect the supplier and confirm quality and delivery capability.", "zh-CN": "我们对供应商进行实地考察，确保其产品质量和交期真实可靠。", "id": "Kami memeriksa pemasok dan memastikan kualitas serta kapasitas pengiriman."},
                "bulletTranslations": {"en": ["Factory audit and certification check", "Pre-shipment inspection and sample confirmation"], "zh-CN": ["实地工厂审计，核验生产线、ISO 认证和出口许可", "出货前检验，确认样品与批量产品一致"], "id": ["Audit pabrik dan sertifikasi", "Inspeksi sebelum pengiriman dan konfirmasi sampel"]},
                "enabled": True,
            },
            {
                "id": "reason-certification",
                "number": "3",
                "title": "全球认证前置服务",
                "subtitle": "合规先行，一次通关",
                "quote": "所有采购产品均符合国际标准，包括 CE、IEC、ISO 等认证。",
                "bullets": ["欧盟、美国、中东和东南亚认证路线梳理", "支付定金前提供认证路线图，避免到港退运"],
                "titleTranslations": {"en": "Certification front service", "zh-CN": "全球认证前置服务", "id": "Layanan sertifikasi awal"},
                "subtitleTranslations": {"en": "Compliance before shipment", "zh-CN": "合规先行，一次通关", "id": "Patuh sebelum dikirim"},
                "quoteTranslations": {"en": "Products are prepared around CE, IEC, ISO and regional requirements.", "zh-CN": "所有采购产品均符合国际标准，包括 CE、IEC、ISO 等认证。", "id": "Produk disiapkan sesuai CE, IEC, ISO dan kebutuhan regional."},
                "bulletTranslations": {"en": ["Route checks for EU, US, Middle East and Southeast Asia", "Certification document package before delivery"], "zh-CN": ["欧盟、美国、中东和东南亚认证路线梳理", "支付定金前提供认证路线图，避免到港退运"], "id": ["Pemetaan sertifikasi EU, US, Timur Tengah dan Asia Tenggara", "Dokumen sertifikasi sebelum pengiriman"]},
                "enabled": True,
            },
            {
                "id": "reason-delivery",
                "number": "4",
                "title": "DDP / EXW 双模式交付",
                "subtitle": "灵活可控，端到端兜底",
                "quote": "我们提供端到端订单管理，最大限度降低采购风险和总成本。",
                "bullets": ["DDP 包含报关、海运、清关、关税缴纳和尾程配送", "EXW 适合多工厂集中采购与二次集货"],
                "titleTranslations": {"en": "DDP / EXW delivery modes", "zh-CN": "DDP / EXW 双模式交付", "id": "Mode pengiriman DDP / EXW"},
                "subtitleTranslations": {"en": "Flexible and controllable", "zh-CN": "灵活可控，端到端兜底", "id": "Fleksibel dan terkendali"},
                "quoteTranslations": {"en": "Choose factory pickup or door-to-door managed delivery.", "zh-CN": "我们提供端到端订单管理，最大限度降低采购风险和总成本。", "id": "Pilih pickup pabrik atau door-to-door managed delivery."},
                "bulletTranslations": {"en": ["Export declaration, shipping, customs and final delivery", "Lower internal logistics cost and supply-chain risk"], "zh-CN": ["DDP 包含报关、海运、清关、关税缴纳和尾程配送", "EXW 适合多工厂集中采购与二次集货"], "id": ["Deklarasi ekspor, shipping, customs dan pengiriman akhir", "Turunkan risiko logistik internal"]},
                "enabled": True,
            },
            {
                "id": "reason-flexible-orders",
                "number": "5",
                "title": "低起订量与灵活订单",
                "subtitle": "小单快反，降低试错门槛",
                "quote": "我们提供低起订量、快速交付和全球运输服务。",
                "bullets": ["样品单、试订单、批量单分阶段推进", "支持 OEM/ODM 定制、多语言说明书和本地化包装"],
                "titleTranslations": {"en": "Low MOQ and flexible orders", "zh-CN": "低起订量与灵活订单", "id": "MOQ rendah dan order fleksibel"},
                "subtitleTranslations": {"en": "Samples, trial orders and batches", "zh-CN": "小单快反，降低试错门槛", "id": "Sample, trial dan batch"},
                "quoteTranslations": {"en": "Start small, validate compatibility, then scale.", "zh-CN": "我们提供低起订量、快速交付和全球运输服务。", "id": "Mulai kecil, validasi kompatibilitas, lalu scale."},
                "bulletTranslations": {"en": ["Sample order, trial order and bulk order paths", "OEM/ODM labels, packaging and multilingual documents"], "zh-CN": ["样品单、试订单、批量单分阶段推进", "支持 OEM/ODM 定制、多语言说明书和本地化包装"], "id": ["Jalur sample, trial dan bulk order", "Label OEM/ODM, packaging dan dokumen multibahasa"]},
                "enabled": True,
            },
            {
                "id": "reason-after-sales",
                "number": "6",
                "title": "双轨售后维修体系",
                "subtitle": "海外本地修 or 原厂返修",
                "quote": "即使交付完成后，我们仍随时协助处理问题。",
                "bullets": ["授权维修中心配备原厂备件，覆盖常见故障", "复杂故障可原厂返修并提供备用机方案"],
                "titleTranslations": {"en": "After-sales repair network", "zh-CN": "双轨售后维修体系", "id": "Jaringan after-sales"},
                "subtitleTranslations": {"en": "Local repair or factory return", "zh-CN": "海外本地修 or 原厂返修", "id": "Repair lokal atau kembali pabrik"},
                "quoteTranslations": {"en": "Delivery does not end service. We help resolve faults quickly.", "zh-CN": "即使交付完成后，我们仍随时协助处理问题。", "id": "Pengiriman bukan akhir layanan. Kami membantu menyelesaikan masalah."},
                "bulletTranslations": {"en": ["Local authorized repair and spare parts", "Factory return repair with backup plan"], "zh-CN": ["授权维修中心配备原厂备件，覆盖常见故障", "复杂故障可原厂返修并提供备用机方案"], "id": ["Repair lokal dan spare part", "Return pabrik dengan rencana cadangan"]},
                "enabled": True,
            },
        ],
    },
    "homeProcurementModes": [
        {
            "id": "mode-a",
            "badge": "模式 A",
            "title": "自主选品 · 统一询价",
            "copy": "浏览产品库，将所需设备加入订单中心，平台根据您的选型清单统一核算报价，省去逐一询价的繁琐。",
            "steps": ["浏览商品", "加入订单", "统一询价", "平台报价"],
            "action": "进入产品库选品",
            "to": "/products",
            "badgeTranslations": {"en": "Mode A", "zh-CN": "模式 A", "id": "Mode A"},
            "titleTranslations": {"en": "Self-select products, one quote", "zh-CN": "自主选品 · 统一询价", "id": "Pilih produk, satu penawaran"},
            "copyTranslations": {
                "en": "Browse the catalog, add required equipment to your list, and receive one reviewed quotation.",
                "zh-CN": "浏览产品库，将所需设备加入订单中心，平台根据您的选型清单统一核算报价，省去逐一询价的繁琐。",
                "id": "Jelajahi katalog, masukkan peralatan ke daftar, dan terima satu penawaran yang sudah ditinjau.",
            },
            "stepTranslations": {
                "en": ["Browse", "Add items", "Review", "Quote"],
                "zh-CN": ["浏览商品", "加入订单", "统一询价", "平台报价"],
                "id": ["Jelajah", "Tambah", "Review", "Quote"],
            },
            "actionTranslations": {"en": "Enter product library", "zh-CN": "进入产品库选品", "id": "Masuk katalog"},
            "enabled": True,
        },
        {
            "id": "mode-b",
            "badge": "模式 B",
            "title": "提交需求 · 方案报价",
            "copy": "描述您的应用场景与技术参数，平台工程师团队为您定制产品组合方案，并提供整体打包报价。",
            "steps": ["描述需求", "匹配方案", "组合报价", "确认下单"],
            "action": "提交采购需求",
            "to": "/contact",
            "badgeTranslations": {"en": "Mode B", "zh-CN": "模式 B", "id": "Mode B"},
            "titleTranslations": {"en": "Submit demand, receive a solution", "zh-CN": "提交需求 · 方案报价", "id": "Kirim kebutuhan, dapatkan solusi"},
            "copyTranslations": {
                "en": "Describe your scenario and parameters. Engineers prepare an equipment portfolio and package quote.",
                "zh-CN": "描述您的应用场景与技术参数，平台工程师团队为您定制产品组合方案，并提供整体打包报价。",
                "id": "Jelaskan skenario dan parameter. Engineer menyiapkan paket peralatan dan quote.",
            },
            "stepTranslations": {
                "en": ["Describe", "Match", "Package quote", "Confirm"],
                "zh-CN": ["描述需求", "匹配方案", "组合报价", "确认下单"],
                "id": ["Jelaskan", "Cocokkan", "Quote paket", "Konfirmasi"],
            },
            "actionTranslations": {"en": "Submit requirement", "zh-CN": "提交采购需求", "id": "Kirim kebutuhan"},
            "enabled": True,
        },
    ],
    "homeScenarios": [
        {
            "id": "industrial-park",
            "icon": "🏭",
            "title": "工业园区配电",
            "copy": "整厂配电系统规划、变压器扩容、高低压配电柜成套供应。",
            "demand": "我需要工业园区配电方案。",
            "titleTranslations": {"en": "Industrial park distribution", "zh-CN": "工业园区配电", "id": "Distribusi kawasan industri"},
            "copyTranslations": {"en": "Transformer capacity expansion and complete LV distribution supply.", "zh-CN": "整厂配电系统规划、变压器扩容、高低压配电柜成套供应。", "id": "Ekspansi trafo dan paket panel distribusi LV lengkap."},
            "demandTranslations": {"en": "I need an industrial park distribution proposal.", "zh-CN": "我需要工业园区配电方案。", "id": "Saya butuh solusi distribusi kawasan industri."},
            "enabled": True,
        },
        {
            "id": "pv-station",
            "icon": "☀️",
            "title": "光伏电站配套",
            "copy": "逆变器、汇流箱、升压变压器、并网开关柜一站式配套。",
            "demand": "我需要光伏电站设备配套。",
            "titleTranslations": {"en": "PV station package", "zh-CN": "光伏电站配套", "id": "Paket PLTS"},
            "copyTranslations": {"en": "Inverters, combiner boxes, step-up transformers and grid cabinets.", "zh-CN": "逆变器、汇流箱、升压变压器、并网开关柜一站式配套。", "id": "Inverter, combiner box, trafo step-up dan panel grid."},
            "demandTranslations": {"en": "I need a PV station equipment package.", "zh-CN": "我需要光伏电站设备配套。", "id": "Saya butuh paket peralatan PLTS."},
            "enabled": True,
        },
        {
            "id": "ev-charging",
            "icon": "🚗",
            "title": "充电桩建设",
            "copy": "充电模块、配电箱、电缆、计量表计及后台监控系统。",
            "demand": "我需要充电桩建设设备方案。",
            "titleTranslations": {"en": "EV charging site", "zh-CN": "充电桩建设", "id": "Lokasi EV charging"},
            "copyTranslations": {"en": "Charging modules, cabinets, cables, meters and monitoring systems.", "zh-CN": "充电模块、配电箱、电缆、计量表计及后台监控系统。", "id": "Modul charging, kabinet, kabel, meter dan sistem monitoring."},
            "demandTranslations": {"en": "I need an EV charging site equipment plan.", "zh-CN": "我需要充电桩建设设备方案。", "id": "Saya butuh rencana peralatan EV charging."},
            "enabled": True,
        },
        {
            "id": "data-center",
            "icon": "🏢",
            "title": "数据中心供电",
            "copy": "UPS、精密配电柜、PDU、母线槽及备用发电机组。",
            "demand": "我需要数据中心供电支持。",
            "titleTranslations": {"en": "Data center power", "zh-CN": "数据中心供电", "id": "Daya data center"},
            "copyTranslations": {"en": "UPS, precision cabinets, PDU, busbar and backup generator packages.", "zh-CN": "UPS、精密配电柜、PDU、母线槽及备用发电机组。", "id": "UPS, kabinet presisi, PDU, busbar dan generator cadangan."},
            "demandTranslations": {"en": "I need data center power supply support.", "zh-CN": "我需要数据中心供电支持。", "id": "Saya butuh dukungan daya data center."},
            "enabled": True,
        },
        {
            "id": "agricultural-irrigation",
            "icon": "🌾",
            "title": "农业灌溉供电",
            "copy": "户外配电箱、水泵控制柜、电缆敷设及防雷接地系统。",
            "demand": "我需要农业灌溉供电方案。",
            "titleTranslations": {"en": "Agricultural irrigation power", "zh-CN": "农业灌溉供电", "id": "Daya irigasi pertanian"},
            "copyTranslations": {"en": "Outdoor boxes, pump control, cabling and lightning protection.", "zh-CN": "户外配电箱、水泵控制柜、电缆敷设及防雷接地系统。", "id": "Box outdoor, kontrol pompa, kabel dan proteksi petir."},
            "demandTranslations": {"en": "I need an agricultural irrigation power solution.", "zh-CN": "我需要农业灌溉供电方案。", "id": "Saya butuh solusi daya irigasi."},
            "enabled": True,
        },
        {
            "id": "temporary-construction",
            "icon": "🏗️",
            "title": "基建临电工程",
            "copy": "箱式变电站、临时配电箱、电缆租赁及施工用电方案。",
            "demand": "我需要基建临电工程方案。",
            "titleTranslations": {"en": "Temporary construction power", "zh-CN": "基建临电工程", "id": "Daya konstruksi sementara"},
            "copyTranslations": {"en": "Box substations, temporary cabinets, rental cables and site power plans.", "zh-CN": "箱式变电站、临时配电箱、电缆租赁及施工用电方案。", "id": "Gardu box, panel sementara, kabel sewa dan rencana site."},
            "demandTranslations": {"en": "I need a temporary construction power solution.", "zh-CN": "我需要基建临电工程方案。", "id": "Saya butuh solusi daya konstruksi sementara."},
            "enabled": True,
        },
        {
            "id": "energy-storage",
            "icon": "🔋",
            "title": "储能系统集成",
            "copy": "储能变流器、电池管理系统、能量管理系统及集装箱方案。",
            "demand": "我需要储能系统集成方案。",
            "titleTranslations": {"en": "Energy storage integration", "zh-CN": "储能系统集成", "id": "Integrasi ESS"},
            "copyTranslations": {"en": "Storage inverters, battery management and containerized systems.", "zh-CN": "储能变流器、电池管理系统、能量管理系统及集装箱方案。", "id": "Inverter storage, BMS, EMS dan sistem kontainer."},
            "demandTranslations": {"en": "I need an energy storage integration plan.", "zh-CN": "我需要储能系统集成方案。", "id": "Saya butuh rencana integrasi ESS."},
            "enabled": True,
        },
        {
            "id": "smart-grid",
            "icon": "⚡",
            "title": "智能电网改造",
            "copy": "智能电表、配电自动化终端、通信模块及后台主站系统。",
            "demand": "我需要智能电网改造方案。",
            "titleTranslations": {"en": "Smart grid retrofit", "zh-CN": "智能电网改造", "id": "Retrofit smart grid"},
            "copyTranslations": {"en": "Smart meters, automation terminals, communications and backend systems.", "zh-CN": "智能电表、配电自动化终端、通信模块及后台主站系统。", "id": "Meter pintar, terminal otomasi, komunikasi dan sistem backend."},
            "demandTranslations": {"en": "I need a smart grid retrofit plan.", "zh-CN": "我需要智能电网改造方案。", "id": "Saya butuh retrofit smart grid."},
            "enabled": True,
        },
    ],
    "homeSuppliers": [
        {
            "id": "huadian",
            "icon": "🏭",
            "name": "华电电气集团",
            "badge": "战略合作",
            "scope": "主营：变压器、配电柜",
            "nameTranslations": {"en": "Huadian Electric Group", "zh-CN": "华电电气集团", "id": "Huadian Electric Group"},
            "badgeTranslations": {"en": "Strategic", "zh-CN": "战略合作", "id": "Strategis"},
            "scopeTranslations": {"en": "Main: transformers, switchgear", "zh-CN": "主营：变压器、配电柜", "id": "Utama: trafo, switchgear"},
            "enabled": True,
        },
        {
            "id": "zhengtai",
            "icon": "🔌",
            "name": "正泰电器股份",
            "badge": "官方授权",
            "scope": "主营：低压电器、开关",
            "nameTranslations": {"en": "Zhengtai Electric", "zh-CN": "正泰电器股份", "id": "Zhengtai Electric"},
            "badgeTranslations": {"en": "Authorized", "zh-CN": "官方授权", "id": "Authorized"},
            "scopeTranslations": {"en": "Main: LV devices, switches", "zh-CN": "主营：低压电器、开关", "id": "Utama: LV devices, switch"},
            "enabled": True,
        },
        {
            "id": "tbea",
            "icon": "⚡",
            "name": "特变电工",
            "badge": "战略合作",
            "scope": "主营：输变电设备",
            "nameTranslations": {"en": "TBEA", "zh-CN": "特变电工", "id": "TBEA"},
            "badgeTranslations": {"en": "Strategic", "zh-CN": "战略合作", "id": "Strategis"},
            "scopeTranslations": {"en": "Main: power transmission equipment", "zh-CN": "主营：输变电设备", "id": "Utama: transmisi daya"},
            "enabled": True,
        },
        {
            "id": "huitech",
            "icon": "🤖",
            "name": "汇川技术",
            "badge": "官方授权",
            "scope": "主营：变频器、伺服",
            "nameTranslations": {"en": "HuiTech", "zh-CN": "汇川技术", "id": "HuiTech"},
            "badgeTranslations": {"en": "Authorized", "zh-CN": "官方授权", "id": "Authorized"},
            "scopeTranslations": {"en": "Main: inverters, servo systems", "zh-CN": "主营：变频器、伺服", "id": "Utama: inverter, servo"},
            "enabled": True,
        },
        {
            "id": "weisheng",
            "icon": "📊",
            "name": "威胜集团",
            "badge": "战略合作",
            "scope": "主营：电能表、仪表",
            "nameTranslations": {"en": "Weisheng Group", "zh-CN": "威胜集团", "id": "Weisheng Group"},
            "badgeTranslations": {"en": "Strategic", "zh-CN": "战略合作", "id": "Strategis"},
            "scopeTranslations": {"en": "Main: meters and instruments", "zh-CN": "主营：电能表、仪表", "id": "Utama: meter dan instrumen"},
            "enabled": True,
        },
        {
            "id": "yuandong",
            "icon": "🔧",
            "name": "远东电缆",
            "badge": "官方授权",
            "scope": "主营：电力电缆、导线",
            "nameTranslations": {"en": "Yuandong Cable", "zh-CN": "远东电缆", "id": "Yuandong Cable"},
            "badgeTranslations": {"en": "Authorized", "zh-CN": "官方授权", "id": "Authorized"},
            "scopeTranslations": {"en": "Main: power cables and conductors", "zh-CN": "主营：电力电缆、导线", "id": "Utama: kabel daya dan konduktor"},
            "enabled": True,
        },
    ],
    "homeCategoryFallback": [
        {"slug": "generator", "name": "发电设备", "icon": "⚡", "sku": "1,286", "tags": ["同步发电机", "柴油发电机组", "风力发电"], "nameTranslations": {"en": "Generation equipment", "zh-CN": "发电设备", "id": "Peralatan pembangkit"}, "tagTranslations": {"en": ["Synchronous generator", "Diesel generator", "Wind power"], "zh-CN": ["同步发电机", "柴油发电机组", "风力发电"], "id": ["Generator sinkron", "Generator diesel", "Tenaga angin"]}, "enabled": True},
        {"slug": "transformer", "name": "变压器", "icon": "🔌", "sku": "2,450", "tags": ["电源变压器", "干式变压器", "油浸式变压器"], "nameTranslations": {"en": "Transformers", "zh-CN": "变压器", "id": "Transformator"}, "tagTranslations": {"en": ["Power transformer", "Dry transformer", "Oil-immersed"], "zh-CN": ["电源变压器", "干式变压器", "油浸式变压器"], "id": ["Trafo daya", "Trafo kering", "Oil-immersed"]}, "enabled": True},
        {"slug": "switchgear", "name": "配电设备", "icon": "📦", "sku": "3,680", "tags": ["桥架", "线槽", "配电柜", "开关柜"], "nameTranslations": {"en": "Distribution equipment", "zh-CN": "配电设备", "id": "Peralatan distribusi"}, "tagTranslations": {"en": ["Bridge", "Busway", "Distribution cabinet"], "zh-CN": ["桥架", "线槽", "配电柜", "开关柜"], "id": ["Bridge", "Busway", "Panel distribusi"]}, "enabled": True},
        {"slug": "smart-meter", "name": "电力电气", "icon": "💡", "sku": "5,920", "tags": ["开关", "电池", "插座", "接线器"], "nameTranslations": {"en": "Power electrical", "zh-CN": "电力电气", "id": "Kelistrikan"}, "tagTranslations": {"en": ["Switch", "Battery", "Connector"], "zh-CN": ["开关", "电池", "插座", "接线器"], "id": ["Switch", "Baterai", "Konektor"]}, "enabled": True},
        {"slug": "automation", "name": "自动化控制系统", "icon": "🤖", "sku": "4,150", "tags": ["电动机", "低压电器", "工控系统", "PLC控制器", "变频器"], "nameTranslations": {"en": "Automation control", "zh-CN": "自动化控制系统", "id": "Kontrol otomasi"}, "tagTranslations": {"en": ["Motor", "LV device", "PLC controller"], "zh-CN": ["电动机", "低压电器", "工控系统", "PLC控制器", "变频器"], "id": ["Motor", "LV device", "PLC controller"]}, "enabled": True},
        {"slug": "instrument", "name": "电力仪表", "icon": "📊", "sku": "2,890", "tags": ["仪器仪表", "变送器", "传感器", "电能表", "功率分析仪"], "nameTranslations": {"en": "Power instruments", "zh-CN": "电力仪表", "id": "Instrumen daya"}, "tagTranslations": {"en": ["Meter", "Transmitter", "Sensor"], "zh-CN": ["仪器仪表", "变送器", "传感器", "电能表", "功率分析仪"], "id": ["Meter", "Transmitter", "Sensor"]}, "enabled": True},
        {"slug": "cable", "name": "输电设备", "icon": "🔧", "sku": "3,420", "tags": ["电线", "电缆", "绝缘导线", "高压输电", "绝缘子"], "nameTranslations": {"en": "Transmission equipment", "zh-CN": "输电设备", "id": "Peralatan transmisi"}, "tagTranslations": {"en": ["Wire", "Cable", "Insulator"], "zh-CN": ["电线", "电缆", "绝缘导线", "高压输电", "绝缘子"], "id": ["Wire", "Cable", "Insulator"]}, "enabled": True},
        {"slug": "tools", "name": "电力工具及物资", "icon": "🛠️", "sku": "1,680", "tags": ["常用工具", "常用材料", "施工设备", "安全防护", "测试工具"], "nameTranslations": {"en": "Power tools and supplies", "zh-CN": "电力工具及物资", "id": "Tools dan material daya"}, "tagTranslations": {"en": ["Tools", "Materials", "Test equipment"], "zh-CN": ["常用工具", "常用材料", "施工设备", "安全防护", "测试工具"], "id": ["Tools", "Materials", "Test equipment"]}, "enabled": True},
    ],
    "homeProductFallback": [
        {"slug": "dry-transformer-scb13", "name": "MDL-800 干式电力变压器 800KVA 10KV", "tag": "直采", "categorySlug": "transformer", "icon": "🔌", "nameTranslations": {"en": "MDL-800 dry type power transformer 800KVA 10KV", "zh-CN": "MDL-800 干式电力变压器 800KVA 10KV", "id": "MDL-800 dry type power transformer 800KVA 10KV"}, "tagTranslations": {"en": "Direct", "zh-CN": "直采", "id": "Direct"}, "enabled": True},
        {"slug": "three-phase-motor-y2", "name": "Y2-160M-4 三相异步电动机 11KW 380V", "tag": "现货", "categorySlug": "automation", "icon": "⚡", "nameTranslations": {"en": "Y2-160M-4 three-phase asynchronous motor 11KW 380V", "zh-CN": "Y2-160M-4 三相异步电动机 11KW 380V", "id": "Y2-160M-4 three-phase asynchronous motor 11KW 380V"}, "tagTranslations": {"en": "In stock", "zh-CN": "现货", "id": "Stock"}, "enabled": True},
        {"slug": "siemens-plc-s7-1200", "name": "西门子 S7-1200 PLC控制器 6ES7214-1AG40-0XB0", "tag": "认证", "categorySlug": "automation", "icon": "🤖", "nameTranslations": {"en": "SIMATIC S7-1200 PLC controller 6ES7214-1AG40-0XB0", "zh-CN": "西门子 S7-1200 PLC控制器 6ES7214-1AG40-0XB0", "id": "SIMATIC S7-1200 PLC controller 6ES7214-1AG40-0XB0"}, "tagTranslations": {"en": "Certified", "zh-CN": "认证", "id": "Certified"}, "enabled": True},
        {"slug": "high-voltage-cable-hse240", "name": "HSE-240 3×240 高压工业线缆", "tag": "直采", "categorySlug": "cable", "icon": "🔧", "nameTranslations": {"en": "HSE-240 3x240 high-voltage power cable", "zh-CN": "HSE-240 3×240 高压工业线缆", "id": "HSE-240 3x240 high-voltage power cable"}, "tagTranslations": {"en": "Direct", "zh-CN": "直采", "id": "Direct"}, "enabled": True},
        {"slug": "gen1-low-voltage-cabinet", "name": "GEN-1型交流低压配电柜 进线柜 出线柜", "tag": "现货", "categorySlug": "switchgear", "icon": "📦", "nameTranslations": {"en": "GEN-1 AC low-voltage distribution incoming and outgoing cabinet", "zh-CN": "GEN-1型交流低压配电柜 进线柜 出线柜", "id": "GEN-1 AC low-voltage distribution incoming and outgoing cabinet"}, "tagTranslations": {"en": "In stock", "zh-CN": "现货", "id": "Stock"}, "enabled": True},
    ],
    "pages": [
        {
            "key": "product",
            "label": "Product center page",
            "pagePath": "/products",
            "headline": "Power equipment product center",
            "summary": "Configure the product center hero image, page headline and product discovery entry.",
            "heroImageUrl": "/page-assets/products-banner.jpg",
            "format": "technical",
            "seoTitle": "Premium power and electrical products",
            "seoDescription": "Browse certified products with technical specifications and project support.",
            "importEnabled": False,
            "imports": [],
            "blocks": [],
        },
        {
            "key": "solution",
            "label": "Solutions page",
            "pagePath": "/solutions",
            "headline": "Scenario-based solution publishing",
            "summary": "Configure the solutions page hero, left scenario directory, right-side solution content mapping and supplemental modules.",
            "heroImageUrl": "/page-assets/solutions-banner.jpg",
            "format": "case-study",
            "seoTitle": "Power project solutions",
            "seoDescription": "Explore electrical and energy solutions for commercial and industrial projects.",
            "importEnabled": True,
            "imports": [],
            "blocks": [],
        },
        {
            "key": "about",
            "label": "About us page",
            "pagePath": "/about",
            "headline": "针对特定场景采购的工业设备采购方案。",
            "summary": "ExampleCorp 为海外买家对接合格的工业设备制造商、工程服务合作伙伴和本地交付资源。",
            "heroImageUrl": "/page-assets/about-banner.jpg",
            "format": "standard",
            "seoTitle": "关于 ExampleCorp",
            "seoDescription": "了解 ExampleCorp 的工业设备场景采购、供应链协调、售后支持和印尼本地配送能力。",
            "importEnabled": False,
            "imports": [],
            "blocks": [
                {"id": "about-company-intro", "type": "paragraph", "title": "公司简介", "body": "我们是一家专注于工业设备行业的垂直B2B采购平台。我们的使命是将产品选择、技术匹配、供应商协调、安装服务资源和售后规划整合到一个工作流程中，从而简化跨境采购。对于采购方而言，这意味着更少的沟通障碍和更快捷的对比；对于代理商和项目团队而言，这意味着更清晰的询价单、更结构化的产品方案和更透明的交付流程。\n\n我们的使命：让工业、基础设施、能源和商业项目的工业设备采购更便捷、更安全、更透明。"},
                {"id": "about-team-advantages", "type": "specs", "title": "团队优势", "body": "采购顾问: 将买方需求转化为可用于询价的产品清单、技术参数和比较维度。\n电气专家: 支持电压等级、容量、保护、耐腐蚀性和环境需求方面的场景匹配。\n供应商协调员: 协调制造商、安装合作伙伴和备件资源，以实现更可靠的交付。\n售后运营人员: 帮助明确保修范围、本地响应路径、备件包和服务文档。"},
                {"id": "about-supply-after-sales", "type": "specs", "title": "供应链和售后能力", "body": "合格的设备网络: 覆盖变压器、开关设备、电缆、电表、发电机、光伏设备和成套配电解决方案。\n文档支持: 帮助买家在发货前索取证书、测试报告、图纸、装箱单和交货单据。\n维护计划: 根据运行环境推荐备件、耗材和高故障风险部件。\n需求审查: 确认应用场景、负载、环境和合规性要求。\n供应商匹配: 比较产品包装、技术适配性和交付能力。\n订单协调: 跟踪生产、检验、物流和安装接口。\n售后支持: 准备好保修、备件和本地服务响应方案。"},
                {"id": "about-indonesia-delivery", "type": "paragraph", "title": "印尼本地配送能力", "body": "印尼项目经常面临高温、暴雨、沿海盐雾、高湿度和长途物流等挑战。我们的交付流程旨在帮助买家在下单前识别这些风险，然后匹配耐腐蚀产品选项、协调安装、推荐备件以及提供本地后续服务。\n\n本地情境感知：支持工业园区、港口、矿区、商业用地、数据中心和电动汽车充电项目。\n配送协调：协调物流、海关文件、现场交付要求和安装时间。\n风险提醒：重点关注盐雾、雨水渗入、过热降额、防雷和备件问题。"},
                {"id": "about-contact-cta", "type": "cta", "title": "准备好讨论您下一个工业设备需求了吗？", "body": "请分享您的应用场景、地点、环境以及预期交付时间表。我们的团队将协助您将其转化为一份符合询价要求的方案。"},
            ],
        },
        {
            "key": "contact",
            "label": "Contact us page",
            "pagePath": "/contact",
            "headline": "Inquiry entry and sales contact information",
            "summary": "Configure contact form copy, WhatsApp, email, address, map image and response promise.",
            "heroImageUrl": "/page-assets/contact-banner.jpg",
            "format": "landing",
            "seoTitle": "Contact ExampleCorp",
            "seoDescription": "Contact ExampleCorp for product quotation, project support and technical consultation.",
            "importEnabled": False,
            "imports": [],
            "blocks": [],
        },
    ],
}


def get_default_website_config() -> dict[str, object]:
    return deepcopy(DEFAULT_WEBSITE_CONFIG)
